version: "3.8"
services:
  backend:
    image: "dmitriikonnovnn/einstufungstest-oesd:v15.08.20.47"
    ports:
      - "80:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: aws-test


