version: "3.8"
services:
  backend:
    image: "dmitriikonnovnn/einstufungstest-oesd:8.4.2022.23.38.50"
    ports:
      - "80:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: aws-test


