version: "3.8"
services:
  backend:
    image: "dmitriikonnovnn/einstufungstest-oesd:7.8.2022.19.45.46"
    ports:
      - "80:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: aws-test


