version: "3.8"
services:
  backend:
    image: "dmitriikonnovnn/einstufungstest-oesd:8.8.2022.10.59.47"
    ports:
      - "80:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: aws-test


