<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ET ADMIN</title>
    <style>
        body{
            background-color: #3e3e3e;
            color: whitesmoke;
        }
    </style>
</head>
<body>
<h1>Österreichisches Institut Moskau Einstufungstest Creator </h1>
<br>
<h2>Einstufungstest Admin Menü</h2>
<a href="/logout">ausloggen</a>
<br>
<a href="/swagger-ui/index.html#/">API endpoints on Swagger</a>
</body>
</html>